//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

#[allow(unused)]
pub use super::baker::Entity as Baker;
#[allow(unused)]
pub use super::bakery::Entity as Bakery;
#[allow(unused)]
pub use super::cake::Entity as Cake;
#[allow(unused)]
pub use super::cake_baker::Entity as CakeBaker;
#[allow(unused)]
pub use super::user::Entity as User;
